[package]
name = "rust_mock_v1_led_blink"
version = "0.1.0"
authors = ["mkXultra <electrincgoat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.12.0"